"""Initial migration.

Revision ID: 04c0da7c77c2
Revises: 
Create Date: 2022-02-01 17:44:09.822933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c0da7c77c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('srvops', sa.Integer(), nullable=True),
    sa.Column('slmr', sa.Integer(), nullable=True),
    sa.Column('techcap', sa.Integer(), nullable=True),
    sa.Column('gc', sa.Integer(), nullable=True),
    sa.Column('si', sa.Integer(), nullable=True),
    sa.Column('overallrate', sa.Integer(), nullable=True),
    sa.Column('datesent', sa.DateTime(), nullable=True),
    sa.Column('daterec', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('user')
    # ### end Alembic commands ###
