"""Initial migration.

Revision ID: f5b6f432beb7
Revises: fd4563276880
Create Date: 2022-02-01 18:58:03.361617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b6f432beb7'
down_revision = 'fd4563276880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'remarks')
    # ### end Alembic commands ###
